$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    # 自定义资源规格
    - runner:
        # 内存为 cpus x 2(GB)，最大支持 64核
        cpus: 8
      docker:
        image: docker.cnb.cool/dadong.cnb/cloud/os/ubuntu:25.04
        volumes:
          - /workspace/.pnpm-store
          - /workspace/node_modules
      services:
        - vscode
        - docker
      stages:
        - name: 安装依赖
          script:
            # 这里是nextjs构建需要使用的命令
            - npm install -g pnpm
            - pnpm install
      

  tag_push:
    eo_deploy:
      runner:
        cpus: 32
      docker:
        image: node:20-alpine
        volumes:
          - /workspace/.pnpm-store
          - /workspace/node_modules
      stages:
        - name: 安装pnpm
          script:
            - npm install -g pnpm
        - name: 安装依赖
          script:
            - pnpm i
        - name: 构建
          script:
            # 这里是nextjs构建需要使用的命令
            - pnpm run build
        - name: 部署到 eo pages
          imports:
            # 这里导入Edgeone的密钥，可在eopages控制台点击API Token新建
            # 这里是cnb提供的导入变量功能，文件内容为 EO_SECRET: xxxxxxxxxxxxxxxxx
            - https://cnb.cool/haorwen/secrets/-/blob/main/env.yml
          image: tencentcom/deploy-eopages:latest
          # 这里需要使用您的EO_SECRET，在上面imports已经说明
          script: edgeone pages deploy ./build -n action2cnb -t $EO_SECRET